<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/10
 * Time: 10:21
 */
namespace Admin\Controller;
use Admin\Model\AuthGroupModel;

/**
 * 角色
 * Class AuthGroupController
 * @package Admin\Controller
 */
class AuthGroupController extends AdminController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->mod = new AuthGroupModel();
    }

    public function index()
    {
        $res = $this->mod->getListInfo();
        $this->assign('list', $res);
        $this->display();
    }

    public function add()
    {
        if (IS_POST) {
            $data = I('post.');
            (empty($data['title'])) && $this->error('请填写角色名称');
            $data['rules'] = implode(',',$data['rules']);
            $data['status'] = 1;
            $res = $this->mod->insertInfo($data);
            $res === true ? $this->success('添加成功') : $this->error('添加失败');
        } else {
            $rule = D('auth_rule')->getRule();
            $this->assign('rule', $rule);
            $this->display();
        }
    }

    public function edit()
    {
        if (IS_POST) {
            $condition['id'] = I('post.id');
            $data = I('post.');
            $data['rules'] = implode(',',$data['rules']);
            array_shift($data);
            $res = $this->mod->updateInfo($condition, $data);
            $res === true ? $this->success('编辑成功') : $this->error('编辑失败');
        } else {
            $condition['id'] = I('get.id');
            empty($condition['id']) && $this->error('无效参数');
            $res = $this->mod->getInfoById($condition);
            $rule = D('auth_rule')->getRule();

            $this->assign('rule', $rule);
            $this->assign('info', $res);
            $this->display();
        }
    }

    public function delete()
    {
        $condition['id'] = I('post.id');
        empty($condition['id']) && $this->error('无效参数');
        $res = $this->mod->where($condition)->delete();
        if ($res) {
            $this->ajaxReturn(array('status' => true, 'msg' => '删除成功!'));
        } else {
            $this->ajaxReturn(array('status' => false, 'msg' => '删除失败!'));
        }
    }
}