<?php
namespace Admin\Controller;

use Admin\Model\UserInfoDictModel;
use Think\Controller;
use Think\Page;

class UserController extends AdminController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->mod = new UserInfoDictModel();
    }

    public function index()
    {
        $param = I('get.');
        $where = array();
        (!empty($param)) && $where['username'] = array('like', "%{$param['name']}%");
        //总条数
        $count = $this->mod->getCount($where);
        $page = new Page($count, C('PAGE_SIZE'));
        //列表信息
        $res = $this->mod->getListFromPage($where, $page);

        $this->assign('param', $param['name']);
        $this->assign('list', array(
            'total' => $count,
            'list' => $res,
            'page' => $page->show()
        ));
        $this->display();
    }

    public function add()
    {
        if (IS_POST) {
            $data = I('post.');
            dump($data);
            $res = $this->mod->insertUser($data);
            $res === true ? $this->success('添加成功') : $this->error('添加失败');
        } else {
            $sele = D('About')->getDepart();
            $this->assign('sele', $sele);
            $this->display();
        }
    }

    public function edit()
    {
        if (IS_POST) {
            $condition['id'] = I('post.id');
            $data = I('post.');
            array_shift($data);
            $res = $this->mod->updateUser($condition, $data);
            $res === true ? $this->success('编辑成功') : $this->error('编辑失败');
        } else {
            $condition['id'] = I('get.id');
            empty($condition['id']) && $this->error('无效参数');
            $res = $this->mod->getInfoById($condition);
            $sele = D('About')->getDepart();
            $this->assign('sele', $sele);
            $this->assign('info', $res);
            $this->display();
        }
    }

    public function delete()
    {
        $condition['id'] = I('post.id');
        empty($condition['id']) && $this->error('无效参数');
        $res = $this->mod->where($condition)->delete();
        if ($res) {
            $this->ajaxReturn(array('status' => true, 'msg' => '删除成功!'));
        } else {
            $this->ajaxReturn(array('status' => false, 'msg' => '删除失败!'));
        }
    }
}